package com.sedra.goiptv.utils

const val PREF_PARENT_USER = "parent_user"
const val PREF_URL = "url"
const val PREF_PORT = "port"
const val PREF_NAME = "name"
const val EXTRA_TYPE_ID = "type_id"
const val EXTRA_SECTION_ID = "sectionId"
const val EXTRA_TYPE_NAME = "type_name"

const val GET_MOVIES_CATEGORIES_ACTION = "get_vod_categories"
const val GET_SERIES_CATEGORIES_ACTION = "get_series_categories"
const val GET_LIVE_CATEGORIES_ACTION = "get_live_categories"
const val PREF_TOKEN_CHANGED = "token_changed"
const val PREF_TOKEN_VALUE = "token_value"

const val GET_LIVE_STREAMS_ACTION = "get_live_streams"
const val GET_MOVIES_ACTION = "get_vod_streams"
const val GET_SERIES_ACTION = "get_series"
const val GET_EPG_ACTION = "get_short_epg"
const val GET_MOVIE_DETAILS_ACTION = "get_vod_info"
const val GET_SERIES_DETAILS_ACTION = "get_series_info"
const val MOVIE_ID_PARAMETER = "vod_id"
const val STREAM_ID_INTENT_EXTRA = "stream_id"
const val STREAM_EXT = "stream_ext"
const val SERIES_ID_PARAMETER = "series_id"
const val CATEGORY_LIST_INTENT_EXTRA = "category_list"
