package com.sedra.goiptv.utils

import com.sedra.goiptv.data.model.RadioStation

fun getRadioStations(): ArrayList<String>{
    val list = ArrayList<String>()
    list.add("<iframe src=\"https://tunein.com/embed/player/s101739/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s110270/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s143123/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s212844/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s9583/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s130692/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s65628/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s214238/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s210036/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s137023/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s122485/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s270277/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s270278/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s138145/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s37232/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s134738/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s135623/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s108977/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s105647/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s209372/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s235641/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s228360/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s211390/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s301126/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s77338/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s272915/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s88154/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s196672/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s103123/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s157955/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s70704/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s25411/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s154053/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s66859/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s2420/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s37332/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s7136/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s6162/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s87938/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s87936/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s139430/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s107840/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s265976/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s198703/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s96846/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s105673/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s158167/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    list.add("<iframe src=\"https://tunein.com/embed/player/s24883/\" style=\"width:100%; height:100px;\" scrolling=\"no\" frameborder=\"no\"></iframe>")
    return list
}